name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: java version
      run: java -version
    - name: maven version
      run: mvn --version
    - name: python version
      run: python --version
    - name: docker version
      run: docker -v
    - name: nodejs version
      run: node -v
    - name: terraform version
      run: terraform -v
    
